### PR TITLE
Fastfall in NCP

### PR DESCRIPTION
**Pull request by ThisTestUser**
FastFall cannot bypass nocheatplus.

### CODE REVIEW

**Comment by ThisTestUser** [comment]
Uh oh something bugged.

**Comment by MrAnyone** [comment]
hmm :/

**Comment by ThisTestUser** [comment]
https://github.com/ThisTestUser/Wurst-Client/tree/insta_fall
This is is much better.

**Comment by MrAnyone** [comment]
Thanks for noticing that it only works on vanilla servers.

**Comment by ThisTestUser** [comment]
If glide works, then fastfall works. They both change the rate of falling, so you should unblock it.

**Comment by MrAnyone** [comment]
Well, the only way to know that is testing. But I don't have a premium account and getting an alt these days is a pain (since Minecraft Leaks just died). If you could test it for me, I'll be grateful.

**Pull request closed without merging**
